title: ThreelogyVideo
description: >
  In a world dominated by highly scripted, acted out wedding videos, Threelogy has been steadfast and bullishly stubborn in keeping theirs natural, candid and real.  And we wouldn't have it any other way.  And quite frankly, you should too.
baseurl:
url: www.threelogyvideo.com

version: 3.0.3

# Build settings
markdown: kramdown

sass:
    style: compressed

collections:
  video:
    output: true
    permalink: /reel/:path/

prose:
  rooturl: "_video"
  siteurl: "www.threelogyvideo.com"
  metadata:
    _video:
      - name: "published"
        field:
          element: 'hidden'
          value: true

      - name: "title"
        field:
          element: "text"
          label: "title"
