---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
collections: 
upload_dir: ''
public_path: https://res.cloudinary.com/threelogyvideo/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
